/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TypingFrame.java
 *
 * Created on Apr 19, 2011, 1:48:11 PM
 */

package com.typing.gui;

/**
 *
 * @author yescas
 */
public class TypingFrame extends javax.swing.JFrame {

    /** Creates new form TypingFrame */
    public TypingFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typingPanel1 = new com.typing.gui.TypingPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jMenuSpeed = new javax.swing.JMenu();
        jMenuItemSlowSpeed = new javax.swing.JMenuItem();
        jMenuItemMediumSpeed = new javax.swing.JMenuItem();
        jMenuItemFastSpeed = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenuEdit.setText("Edit");

        jMenuSpeed.setText("Speed");

        jMenuItemSlowSpeed.setText("Slow");
        jMenuItemSlowSpeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSlowSpeedActionPerformed(evt);
            }
        });
        jMenuSpeed.add(jMenuItemSlowSpeed);

        jMenuItemMediumSpeed.setText("Medium");
        jMenuItemMediumSpeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMediumSpeedActionPerformed(evt);
            }
        });
        jMenuSpeed.add(jMenuItemMediumSpeed);

        jMenuItemFastSpeed.setText("Fast");
        jMenuItemFastSpeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFastSpeedActionPerformed(evt);
            }
        });
        jMenuSpeed.add(jMenuItemFastSpeed);

        jMenuEdit.add(jMenuSpeed);

        jMenuBar1.add(jMenuEdit);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(typingPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(typingPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemSlowSpeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSlowSpeedActionPerformed
        this.typingPanel1.setSpeed(2);
    }//GEN-LAST:event_jMenuItemSlowSpeedActionPerformed

    private void jMenuItemMediumSpeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMediumSpeedActionPerformed
        this.typingPanel1.setSpeed(3);
    }//GEN-LAST:event_jMenuItemMediumSpeedActionPerformed

    private void jMenuItemFastSpeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFastSpeedActionPerformed
        this.typingPanel1.setSpeed(5);
    }//GEN-LAST:event_jMenuItemFastSpeedActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TypingFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemFastSpeed;
    private javax.swing.JMenuItem jMenuItemMediumSpeed;
    private javax.swing.JMenuItem jMenuItemSlowSpeed;
    private javax.swing.JMenu jMenuSpeed;
    private com.typing.gui.TypingPanel typingPanel1;
    // End of variables declaration//GEN-END:variables

}
